Rewrite Mutex usage
rrromlin/hak pull request #2
Opened 2021-04-21 15:37 UTC by JustCaptcha

2021-04-21 15:49 UTC, remimimimi commented on src/lock.rs
>      }
Try without unnecessary trait. Use wrapper type
```rust
#[repr(transparent)]
pub struct Mutex<T> {
    inner_mutex: spin::Mutex<T>,
}

impl<T> MutexNew<T> {
    fn sleep_lock(&mut self) {
        while let None = self.try_lock() {
            syscall_sleep(DEFAULT_LOCK_SLEEP);
        }
    }
}
```

2021-04-21 15:55 UTC, remimimimi requested changes
Please use new Mutex properly

2021-04-23 15:50 UTC, remimimimi commented on src/lock.rs
> +    pub inner_mutex: spin::Mutex<T>,
Why inner_mutex public?

2021-04-23 15:54 UTC, remimimimi commented on src/process.rs
> +            PROCESS_LIST.inner_mutex.force_unlock();
I think there's no need in force_unlock() because anyway lock will be destructed at the end of block

2021-04-23 15:54 UTC, remimimimi commented on src/process.rs
>          // Return the first instruction's address to execute.
There also

2021-04-23 15:55 UTC, remimimimi commented on src/sched.rs
> +        PROCESS_LIST.inner_mutex.force_unlock();
There's too

2021-04-23 17:32 UTC, remimimimi requested changes
Avoid using force_unlock() because this unnecessary and try to write wrapper functions over spin::Mutex or you can implement Deref and DerefMut traits(prefer second)

2021-04-23 18:33 UTC, JustCaptcha commented on src/process.rs
> +            PROCESS_LIST.inner_mutex.force_unlock();
There are no other unlock methods there:
https://docs.rs/spin/0.9.0/spin/mutex/struct.Mutex.html

2021-04-23 18:33 UTC, JustCaptcha commented on src/lock.rs
> +    pub inner_mutex: spin::Mutex<T>,
Otherwise, how are you supposed to execute internal methods then?

2021-04-23 18:36 UTC, closed without merging